version: '3.9'

services:

  vad:
    stdin_open: true
    tty: true
    image: pawlyglot/vad:1.0.0
    build:
      context: ./services/voice_activity
      dockerfile: dockerfile.vad
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 50052:50052
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb  

  asr:
    stdin_open: true
    tty: true
    image: pawlyglot/asr:1.0.0
    build:
      context: ./services/speech_recognition
      dockerfile: dockerfile.asr
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 50053:50053
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb

  mt:
    stdin_open: true
    tty: true
    image: pawlyglot/mt:1.0.0
    build:
      context: ./services/machine_translation
      dockerfile: dockerfile.mt
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 50054:50054
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb  

  vc:
    stdin_open: true
    tty: true
    image: pawlyglot/vc:1.0.0
    build:
      context: ./services/voice_cloning
      dockerfile: dockerfile.vc
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 50055:50055
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb
