# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vad.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvad.proto\x12\x03vad\"\x1f\n\rDetectRequest\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\"\n\x0e\x44\x65tectResponse\x12\x10\n\x08\x62\x36\x34\x61rray\x18\x01 \x01(\t2N\n\x15VoiceActivityDetector\x12\x35\n\x06\x44\x65tect\x12\x12.vad.DetectRequest\x1a\x13.vad.DetectResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vad_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DETECTREQUEST']._serialized_start=18
  _globals['_DETECTREQUEST']._serialized_end=49
  _globals['_DETECTRESPONSE']._serialized_start=51
  _globals['_DETECTRESPONSE']._serialized_end=85
  _globals['_VOICEACTIVITYDETECTOR']._serialized_start=87
  _globals['_VOICEACTIVITYDETECTOR']._serialized_end=165
# @@protoc_insertion_point(module_scope)
