# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vad_pb2 as vad__pb2


class VoiceActivityDetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.stream_unary(
                '/vad.VoiceActivityDetector/Detect',
                request_serializer=vad__pb2.DetectRequest.SerializeToString,
                response_deserializer=vad__pb2.DetectResponse.FromString,
                )


class VoiceActivityDetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Detect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceActivityDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.stream_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=vad__pb2.DetectRequest.FromString,
                    response_serializer=vad__pb2.DetectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vad.VoiceActivityDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VoiceActivityDetector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/vad.VoiceActivityDetector/Detect',
            vad__pb2.DetectRequest.SerializeToString,
            vad__pb2.DetectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
